{% set name = "hdmf" %}
{% set version = "4.2.0" %}
{% set sha256 = "3555fb39874544ec3cd741b9eccd8db2339fae000e5a51859e5c20c3b0c6d4b5" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - validate_hdmf_spec = hdmf.testing.validate_spec:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - h5py >=3.1
    - jsonschema >=3.2
    - numpy >=1.19.3
    - pandas >=1.2.0
    - ruamel.yaml >=0.16

test:
  source_files:
    - tests
  requires:
    - pytest
    - python {{ python_min }}
  imports:
    - hdmf
    - hdmf.common
  commands:
    - pytest -v

about:
  home: https://github.com/hdmf-dev/hdmf
  license: BSD-3-Clause
  license_file: license.txt
  summary: A Python API for working with hierarchical object data
  description: |
    The Hierarchical Data Modeling Framework, or HDMF is a Python package
    for working with hierarchical data. It provides APIs for specifying data
    models, reading and writing data to different storage backends, and
    representing data with Python object.
  doc_url: http://hdmf.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - ajtritt
    - rly
    - oruebel
    - mavaylon1
