{% set name = "hdmf" %}
{% set version = "2.5.8" %}
{% set sha256 = "c719bd2aa50a0e7be81227b7681045cb43d9d9b85d3623d3f571836ba3cd396a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python >=3.6
    - setuptools
    - h5py >=2.9,<3
    - numpy >=1.16,<1.21
    - scipy >=1.1,<2
    - pandas >=1.0.5,<2
    - ruamel.yaml >=0.15,<1
    - jsonschema >=2.6.0,<4

test:
  imports:
    - hdmf

about:
  home: https://github.com/hdmf-dev/hdmf
  license: BSD-3-Clause
  license_file: license.txt
  summary: A Python API for working with hierarchical object data
  description: |
    The Hierarchical Data Modeling Framework, or HDMF is a Python package
    for working with hierarchical data. It provides APIs for specifying data
    models, reading and writing data to different storage backends, and
    representing data with Python object.
  doc_url: http://hdmf.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - ajtritt
    - rly
    - oruebel
