travis:
  secure:
    BINSTAR_TOKEN: HuwzEgTF4Gduf0wjJCjk1w0gZr3TXR+1uxE2A2fdbx2zWk6TGgzIDBYdMVbGH/tLhyTwht+2tf996H+VNtfiJVMlL06gNTnvIWADCCFp4HD8lKqtL07wsBeZNlqkfnbyVv1S2Vb6iIakKwsTl8zTdfNnEhlaTdmiBeEfgsZJw1tN96YPC9m33d9L5/ada+jFNHxoucs0TyLmc0vzEpod/gte/zIRLSdzhhVHp4Ix5AzZHcXU7lAVUzyPBBZLI5COOUJTD4+bMcIpiBSknt8xqq6Spox+L7MM+IQDIbj6PAvREiBlNJ2EjwvQu3JMsthwVqrrCRtddm2U2a0GqsUqjJODl7m5Xki7x6PlkvXIgxbzhE+7lW5/ACrc2keIa/AzBy8OnY/VbQXBxcNKul0xbAo+tA7t4qVj3yoBBRcZlOOCgolnjR+uRLzPRrOnIr8Vl7YZI37cy2kpK/ffEKmR0W/Y4krnZNe5FuVy/NDFl6atzCNFbPyqG0XC6jwkT4s6ADchX9p5tx0STs+pB3FNH0tEznaRxqQ+etm4I59G21GbcemVF7AcPB7IKjVJjTUyUviKNxb72IBCvM7dvGsiheQYvl+I7U9tx/NHJbyTkOd+U7T6EcXHik8sVA0H8nFGFyonZUQXsSN+v3Ou1QaExOz/24T7UipU+va7HTMYX30=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
